apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f es.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: es01
  name: es01
  namespace: ragflow
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: es01
