kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ragflow-pvc
  namespace: ragflow
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi