apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-merged.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: ragflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --max_connections=1000
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password
            - --binlog_expire_logs_seconds=604800
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ragflow-config
                  key: MYSQL_PASSWORD
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_HOST
              value: "%"
          name: ragflow-mysql
          image: mysql:8.0.39
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
              subPath: ragflow/volumes/mysql/data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-cm1
              subPath: init.sql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: ragflow-pvc
        - name: mysql-cm1
          configMap:
            items:
              - key: init.sql
                path: init.sql
            name: mysql-cm1