kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: es01
  namespace: ragflow
  labels:
    io.kompose.service: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  template:
    metadata:
      labels:
        io.kompose.service: es01
    spec:
      containers:
        - name: ragflow-es-01
          image: elasticsearch:8.11.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: restapi
              containerPort: 9200
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ragflow-config
          env:
            - name: ELASTIC_PASSWORD
              value: infini_rag_flow
            - name: TZ
              value: Asia/Shanghai
            - name: bootstrap.memory_lock
              value: 'false'
            - name: cluster.routing.allocation.disk.watermark.flood_stage
              value: 2gb
            - name: cluster.routing.allocation.disk.watermark.high
              value: 3gb
            - name: cluster.routing.allocation.disk.watermark.low
              value: 5gb
            - name: discovery.type
              value: single-node
            - name: node.name
              value: es01
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.transport.ssl.enabled
              value: 'false'
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 0.5Gi
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
              subPath: ragflow/volumes/elasticsearch/data
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: ragflow-pvc


