apiVersion: v1
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS rag_flow;
    USE rag_flow;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql
  name: mysql-cm1
  namespace: ragflow
