apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-merged.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio
  name: minio
  namespace: ragflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  template:
    metadata:
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - --console-address
            - :9001
            - /data
          envFrom:
            - configMapRef:
                name: ragflow-config
          env:
            - name: MINIO_ROOT_PASSWORD
              value: infini_rag_flow
            - name: MINIO_ROOT_USER
              value: rag_flow
            - name: TZ
              value: Asia/Shanghai
          image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
          imagePullPolicy: IfNotPresent
          name: ragflow-minio
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - mountPath: /data
              name: minio-data
              subPath: ragflow/volumes/minio/data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: ragflow-pvc