apiVersion: v1
kind: PersistentVolume
metadata:
  name: ragflow
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfs_share
    server: 172.16.0.72